import { z } from 'zod';

/**
 * Supported currency codes for SSM-Pay
 */
export const CurrencyEnum = z.enum(['NGN', 'USD', 'GBP', 'EUR'], {
  errorMap: () => ({ message: 'Invalid currency. Must be NGN, USD, GBP, or EUR' }),
});

/**
 * Supported payment methods
 */
export const PaymentMethodEnum = z.enum(['card', 'bank_transfer', 'wallet', 'ussd'], {
  errorMap: () => ({ message: 'Invalid payment method. Must be card, bank_transfer, wallet, or ussd' }),
});

/**
 * Transaction status enum for callbacks and verification
 */
export const TransactionStatusEnum = z.enum(['success', 'failed', 'pending', 'cancelled'], {
  errorMap: () => ({ message: 'Invalid transaction status' }),
});

/**
 * Schema for validating email addresses with custom error messages
 */
export const EmailSchema = z.string({
  required_error: 'Email address is required',
  invalid_type_error: 'Email must be a string',
}).email({
  message: 'Please enter a valid email address',
}).max(254, {
  message: 'Email address is too long (max 254 characters)',
});

/**
 * Schema for validating monetary amounts
 */
export const AmountSchema = z.number({
  required_error: 'Amount is required',
  invalid_type_error: 'Amount must be a number',
}).positive({
  message: 'Amount must be greater than zero',
}).max(10000000, {
  message: 'Amount exceeds maximum allowed value of ₦10,000,000',
});

/**
 * Schema for validating transaction references
 */
export const ReferenceSchema = z.string({
  required_error: 'Transaction reference is required',
}).min(6, {
  message: 'Reference must be at least 6 characters',
}).max(100, {
  message: 'Reference is too long (max 100 characters)',
});

/**
 * Payment initialization schema
 * Used when a customer initiates a new payment transaction
 */
export const PaymentInitSchema = z.object({
  /** Customer's email address for receipt and notifications */
  email: EmailSchema,
  
  /** Payment amount in the specified currency's smallest unit (kobo for NGN) */
  amount: AmountSchema,
  
  /** ISO 4217 currency code - defaults to Nigerian Naira */
  currency: CurrencyEnum.default('NGN'),
  
  /** Preferred payment method - optional, allows customer to choose on checkout */
  paymentMethod: PaymentMethodEnum.optional(),
  
  /** Unique identifier for the customer from your system */
  customerId: z.string()
    .min(1, { message: 'Customer ID cannot be empty' })
    .max(100, { message: 'Customer ID is too long' })
    .optional(),
  
  /** Optional description of what the payment is for */
  description: z.string()
    .max(500, { message: 'Description too long (max 500 characters)' })
    .optional(),
  
  /** Mobile number for USSD payments and notifications */
  mobileNumber: z.string()
    .regex(/^(\+?234|0)[789]\d{9}$/, {
      message: 'Invalid Nigerian phone number format',
    })
    .optional(),
  
  /** Custom metadata to attach to the transaction */
  metadata: z.record(z.unknown(), z.unknown()).optional(),
  
  /** Redirect URL after payment completion */
  redirectUrl: z.string()
    .url({ message: 'Invalid redirect URL format' })
    .optional(),
  
  /** Unique reference generated by merchant for idempotency */
  merchantReference: ReferenceSchema.optional(),
});

/**
 * Payment callback schema
 * Used to validate webhook callbacks from payment providers
 */
export const PaymentCallbackSchema = z.object({
  /** Unique transaction identifier from payment provider */
  transactionId: z.string({
    required_error: 'Transaction ID is required',
  }).min(1, { message: 'Transaction ID cannot be empty' }),
  
  /** Current status of the transaction */
  status: TransactionStatusEnum,
  
  /** Merchant's original reference for this transaction */
  reference: ReferenceSchema,
  
  /** Transaction amount in smallest currency unit */
  amount: z.number({
    required_error: 'Amount is required',
  }).nonnegative({ message: 'Amount cannot be negative' }),
  
  /** ISO 4217 currency code */
  currency: z.string()
    .length(3, { message: 'Currency must be 3-character ISO code' })
    .uppercase(),
  
  /** ISO 8601 datetime string of when callback was sent */
  timestamp: z.string()
    .datetime({ message: 'Invalid datetime format. Use ISO 8601 format' }),
  
  /** Payment method used by customer */
  paymentMethod: PaymentMethodEnum.optional(),
  
  /** Additional data from payment provider */
  metadata: z.record(z.unknown(), z.unknown()).optional(),
  
  /** Digital signature for verifying callback authenticity */
  signature: z.string().optional(),
});

/**
 * Payment verification schema
 * Used when verifying a completed transaction
 */
export const PaymentVerifySchema = z.object({
  /** Transaction reference to verify */
  reference: ReferenceSchema,
  
  /** Expected amount for additional validation */
  expectedAmount: AmountSchema.optional(),
  
  /** Expected currency for additional validation */
  expectedCurrency: CurrencyEnum.optional(),
});

/**
 * Refund schema for processing refunds
 */
export const RefundSchema = z.object({
  /** Original transaction reference */
  transactionRef: ReferenceSchema,
  
  /** Refund amount - must not exceed original */
  refundAmount: AmountSchema,
  
  /** Reason for the refund */
  reason: z.string()
    .min(5, { message: 'Reason must be at least 5 characters' })
    .max(500, { message: 'Reason too long' }),
  
  /** Optional refund reference for tracking */
  refundReference: ReferenceSchema.optional(),
});

/**
 * Inferred types from schemas for use throughout the application
 */
export type PaymentInitInput = z.infer<typeof PaymentInitSchema>;
export type PaymentCallbackInput = z.infer<typeof PaymentCallbackSchema>;
export type PaymentVerifyInput = z.infer<typeof PaymentVerifySchema>;
export type RefundInput = z.infer<typeof RefundSchema>;

/** Validated and parsed output types */
export type PaymentInitOutput = z.output<typeof PaymentInitSchema>;
export type PaymentCallbackOutput = z.output<typeof PaymentCallbackSchema>;
export type PaymentVerifyOutput = z.output<typeof PaymentVerifySchema>;
export type RefundOutput = z.output<typeof RefundSchema>;
